ICHIRO_WINNERS = [
    ('McSkrtrabool', 0),
    ('Prime GC', 0),
    ('picnicmou', 1),
    ('Xy', 0),
    ('Herman', 1),
    ('SmrtAlec', 2),
    ('NZ', 1),
    ('scarp3 | L.O', 0),
    ('Matthew', 1),
    ('eaten', 1),
    ('bUU', 1),
    ('fifi', 1),
    ('Gitster', 0),
    ('Day', 1),
    ('Ject | Shikigai', 0),
    ('Jayyyyy', 0),
    ('VeiChern', 0),
    ('xiaoman', 0),
    ('NOSAJ | Oikos', 1),
    ('popokodel', 1),
    ('TGG-TEHAHAHA', 0),
    ('Kaiman', 1),
    ('Pyyeapy', 0),
    ('Bamboo', 0),
    ('Cookieeee', 0),
    ('dumb_m0ney', 0),
    ('🎀Angelinebaby🎀', 1),
    ('MALΞK', 1),
    ('WantanMee', 1)
]

JIRO_WINNERS = [
    ('Annabelle', 0),
    ('0xProFab.AAA', 2),
    ('ferenyx | AnimeMeta', 0),
    ('mikel', 0),
    ('ball | AnimeMeta', 1),
    ('Akdevil', 1),
    ('night23', 0),
    ('AKUMA', 0),
    ('JayJay', 1),
    ('KaI1ive', 1),
    ('D.T', 1),
    ('wokring | AnimeMeta', 0),
    ('huggy', 0),
    ('Morileck', 0),
    ('Jet', 0),
    ('DegenTrading', 0),
    ('umpah umpah', 1),
    ('Maienka', 2),
    ('!Nootor', 0),
    ('Aesuke', 2),
    ('Sm4ug', 2),
    ('AliAliCoffee', 1),
    ('Touchdeath', 0),
    ('darylbintl', 0),
    ('wilsontiger', 0),
    ('Ace | Jiro', 1),
    ('Goddamm', 0),
    ('ESOOO🪐', 0),
]

SABURO_WINNERS = [
    ('Mojojojo', 2),
    ('Wintermeister', 0),
    ('bones', 0),
    ('cenay| Saburo', 0),
    ('Travy J', 0),
    ('Lady_D', 0),
    ('dwightshrute', 2),
    ('KongKou', 2),
    ('Checkmate', 2),
    ('ye', 2),
    ('bonnn', 1),
    ('treytastic', 0),
    ('Fei | Mcfly', 1),
    ('NFTFly', 0),
    ('geksim', 0),
    ('SOS', 1),
    ('0x1k', 1),
    ('xxxDreamer', 2),
    ('guaiboi', 0),
    ('zeuspapa', 0),
    ('düüd', 0),
    ('archie', 2),
    ('puddin’', 1),
    ('ahDY', 0),
    ('PepeKnowMe', 0),
    ('Ryden', 2),
    ('shrek', 1),
    ('🐳 🥓 特罗兹 🥓🐳', 0),
    ('Suhspect', 0),
    ('Dumb', 1)
]

DRAWER_WINNERS = [
    ('Herman', 1),
    ('ye', 2),
    ('Annabelle', 0),
    ('fifi', 1),
    ('ferenyx | AnimeMeta', 0),
    ('0xProFab.AAA', 2),
    ('Checkmate', 2),
    ('ball | AnimeMeta', 1),
    ('mikel', 0),
    ('bones', 0),
    ('guaiboi', 0),
    ('Mojojojo', 2),
    ('treytastic', 0),
    ('Akdevil', 1),
    ('night23', 0),
    ('SOS', 1),
    ('xxxDreamer', 2),
    ('🐳 🥓 特罗兹 🥓🐳', 0),
    ('JayJay', 1),
    ('Wintermeister', 0),
    ('KongKou', 2),
    ('geksim', 0),
    ('puddin’', 1),
    ('0x1k', 1),
    ('D.T', 1),
    ('picnicmou', 1),
    ('bonnn', 1),
    ('Matthew', 1),
    ('FlyingFish', 0),
    ('Xy', 0),
    ('KaI1ive', 1),
    ('PepeKnowMe', 0),
    ('Jet', 0),
    ('Rain.Dazzler', 0),
    ('huggy', 0),
    ('AKUMA', 0),
    ('Gitster', 0),
    ('Ryden', 2),
    ('zeuspapa', 0),
    ('wino', 0),
    ('cenay| Saburo', 0),
    ('Prime GC', 0),
    ('eaten', 1),
    ('xiaoman', 0),
    ('archie', 2),
    ('Fei | Mcfly', 1),
    ('NFTFly', 0),
    ('Morileck', 0),
    ('Touchdeath', 0),
    ('darylbintl', 0),
    ('CWJacky', 0),
    ('ONI x doMINation', 0),
    ('wilsontiger', 0),
    ('Ace | Jiro', 1),
    ('Suhspect', 0),
    ('DegenTrading', 0),
    ('doc.Trinity', 1),
    ('Dumb', 1),
    ('Goddamm', 0),
    ('ESOOO🪐', 0),
    ('düüd', 0)
]